### ISSUE TITLE
Ensure all functionality is covered by tests

### ISSUE THREAD

**Issue by mkborregaard** [JuliaPlots/Plots.jl#1225]
We want to make sure that all functionality that's been added to Plots over the last year or so is covered by the test suite. For reference I've posted the most recent version of the News.md file below - we can use the check boxes to mark which are covered in examples (ideally we should note the number of the example too).

## 0.13.1

- [ ] fix a bug when passing a vector of functions with no bounds (e.g. `plot([sin, cos])`)
- [x] export `pct` and `px` from Plots.PlotMeasures

## 0.13.0
- [x] no longer export `w`, `h` and names from Measures.jl; use `using Plots.PlotMeasures` to get these names back
- [ ] `bar_width` now depends on the minimum distance between bars, not the mean
- [ ] better automatic x axis limits for plotting Functions
- [ ] `tick_direction` attribute now allows ticks to be on the inside of the plot border
- [ ] allow `plot([])` to generate an empty plot
- [x] add `origin` framestyle
- [ ] GR now has `line_z` and `fill_z` attributes for determining the color of shapes and lines
- [ ] fix logscale bug error for values < 1e-16 on pyplot
- [ ] fix an issue on pyplot where >1 colorbar would be shown if there was >1 series

## 0.12.4

- [x] added a new `framestyle` argument with choices: :box, :semi, :axes, :grid and :none
- [ ] group now groups keyword arguments of the same length as the input
- [x] allow passing DateTime objects as ticks
- [ ] allow specifying the number of ticks as an integer
- [ ] better margin with room for text
- [ ] added a `match` option for linecolor

## 0.12.3
- [ ] `grid` is now an axis attribute and a magic argument: it is now possible to modify the grid line style, alpha and line width
- [x] fix GR colorbar for scatter plots

#### 0.12.1

- [ ] add surface alpha for Plotly(JS)
- [ ] add fillrange to Plotly(JS)

#### 0.11.3

- [x] support for legend position in GR
- [x] `legendtitle` attribute added

#### 0.11.0

- [ ] added a `:stephist` and `:scatterhist` series type as well as ``:barhist` (the default)
- [ ] support for log scale axes with histograms
- [ ] support for plotting `StatsBase.Histogram`
- [ ] allowing bins to be specified as `:sturges`, `:rice`, `:scott` or :fd
- [ ] allow `normalization` to be specified as :density (for unequal bins) or :pdf (sum to 1)
- [ ] add `fill_z` attribute for pyplot
- [ ] improved tick positions for TimeType x axes
- [ ] support for improved color gradient capability in PlotUtils
- [ ] add a showlibrary recipe to display color libraries
- [ ] add a showgradient recipe to display color gradients

#### 0.9.5
- [ ] DateTime recipe
- [ ] reset theme with theme(:none)
- [ ] fix plotly lims for log scale

#### 0.9.4

- [ ] histogram2d puts NaN for zeros
- [ ] improved support of NaN in heatmaps
- [ ] consistent aspect_ratio

#### 0.9.1

- [ ] `axis = nothing` magic
- [ ] fix clim for line_z

#### 0.9.0
- [ ] new axis formatter attribute... accepts functions to convert numbers to strings

#### 0.8.0
- [ ] bar_width support
- [ ] horizontal bars

## 0.7
- [x] added `contourf` seriestype
- [ ] allow `plt[1]` to return first Subplot
- [ ] allow `sp[1]` to return the first Series of the Subplot

#### 0.7.3
- [ ] `cgrad` method for easy color gradient creation
- [ ] `link = :square` option

#### 0.7.2

- [ ] line_z arg for multicolored line segments
- [ ] `curves` series type
- [ ] `iter_segments` iterator

#### 0.7.1

- [x] inset (floating) subplots
- [ ] new clims attribute
- [ ] bbox `h_anchor`/`v_anchor`
- [ ] new axis arg: `:link` is a list of subplots to link axes with

#### 0.7.0
- [ ] New `link_axes` functionality
- [ ] Brand new subplot layout mechanics:
- [ ] `@layout` macro

- [ ] Added `series_annotations` attribute (previously that functionality was merged with `annotations`, which are not series-specific)

#### 0.6.2
- [x] Support for image display
- [ ] `arrow` keyword and support for adding arrows to paths

#### 0.6.1
- [ ] `rotation` keyword

#### 0.6.0
- [ ] [boxplot/violin recipes](https://github.com/tbreloff/ExamplePlots.jl/blob/master/notebooks/boxplot.ipynb)
- [x] [errorbar/ribbon recipes](https://github.com/tbreloff/ExamplePlots.jl/blob/master/notebooks/errorbars.ipynb)
- [ ] [quiver recipe](https://github.com/tbreloff/ExamplePlots.jl/blob/master/notebooks/quiver.ipynb)
- [x] `polar` coordinates
- [ ] `normalize` and `weights` keywords
- [ ] background/foreground subcategories for fine-tuning of looks
- [ ] `add_theme`/`set_theme` and ggplot2 theme (see [this issue](https://github.com/tbreloff/Plots.jl/issues/201))
- [ ] support for non-gridded surfaces with pyplot's trisurface

#### 0.5.4
- [ ] new `shape` linetype for plotting polygons in plot-coordinates (see https://github.com/tbreloff/ExamplePlots.jl/blob/master/notebooks/batman.ipynb)

#### 0.5.3

- [x] `@gif` macro with `every`/`when` syntax
- [ ] bezier curves and other graph drawing helpers

#### 0.5.2

- [x] Added [GR.jl](https://github.com/jheinen/GR.jl) as a backend (unfinished but functional) All credit to @jheinen
- [x] Set defaults within backend calls (i.e. `gadfly(legend=false)`)
- [ ] `abline!`; also extrema allows plotting functions without giving x (i.e. `plot(cos, 0, 10); plot!(sin)`) @pkofod @joshday
- [ ] Integration with [PlotlyJS.jl](https://github.com/spencerlyon2/PlotlyJS.jl) for using Plotly inside a Blink window @spencerlyon2
- [ ] Overhaul to `:legend` keyword (see https://github.com/tbreloff/Plots.jl/issues/135)
- [ ] Support for plotting lists of Tuples and FixedSizeArrays
- [ ] new `@animate` macro for super simple animations (see https://github.com/tbreloff/Plots.jl/issues/111#issuecomment-181515616)
- [ ] allow Function for `:fillrange` and `zcolor` arguments (for example: `scatter(sin, 0:10, marker=15, fill=(cos,0.4), zcolor=sin)`)
- [ ] allow vectors of PlotText without x/y coords (for example: `scatter(rand(10), m=20, ann=map(text, 1:10))`)

#### 0.5.0

- [x] `with` function for temporary defaults
- [x] contours
- [x] basic 3D plotting
- [ ] `stroke` and `brush` for more fine-tuned control over visuals
- [ ] smarter "magic" arguments: `line`, `marker`

**Comment by mkborregaard** [comment]
Whenever someone's got a minute we can run over this list and add ticks where appropriate.

**Comment by daschw** [comment]
Awesome! Great idea!

**Comment by t-bltg** [comment]
We now have around `91%` coverage.
