### ISSUE TITLE
errors on 1.0

### ISSUE THREAD

**Issue by mkborregaard** [JuliaPlots/Plots.jl#1631]
Suddenly 1.0 is out, and people expect Plots to work.

There are a number of errors that I did not see as deprecations on 0.7. They come only sequentially (once you've fixed one the next appears) but here's a list.

- [x] An old `endof`, needs now to be `lastindex` - I've made a fix here: #1626 
- [x] There is still two uses of the old iterator protocol, with `start`, `next` and `done`- I've attempted a fix here, but I'm quite uncertain about how to update to the new protocol: #1628 
- [x] `mimewritable` should now be `showable` I think? Attempted fix here: #1629
- [x] I think it is no longer necessary to overload `broadcast` for `Measures`?
- [x] I think `readstring` should just be `read` now.
EDIT - I've just collected all in #1630
With these fixed, you can `using ` the package, but it will still not plot, with the error message:
```
ERROR: MethodError: no method matching Array{RGBA{Float64},N} where N(::Tuple{Int64})
Closest candidates are:
  Array{RGBA{Float64},N} where N(::UndefInitializer, ::Int64) where T at boot.jl:408
  Array{RGBA{Float64},N} where N(::UndefInitializer, ::Int64, ::Int64) where T at boot.jl:409
  Array{RGBA{Float64},N} where N(::UndefInitializer, ::Int64, ::Int64, ::Int64) where T at boot.jl:410
  ...
Stacktrace:
 [1] plot_color(::Array{RGB{FixedPointNumbers.Normed{UInt8,8}},1}) at /Users/michael/.julia/packages/PlotUtils/xQ9v/src/colors.jl:24
 [2] generate_colorgradient(::RGBA{Float64}) at /Users/michael/.julia/packages/PlotUtils/xQ9v/src/color_utils.jl:51
 [3] get_color_palette(::Symbol, ::RGBA{Float64}, ::Int64) at /Users/michael/.julia/packages/PlotUtils/xQ9v/src/color_utils.jl:65
 [4] _update_subplot_colors(::Plots.Subplot{Plots.GRBackend}) at /Users/michael/.julia/dev/Plots/src/args.jl:1411
 [5] _update_subplot_args(::Plots.Plot{Plots.GRBackend}, ::Plots.Subplot{Plots.GRBackend}, ::Dict{Symbol,Any}, ::Int64, ::Bool) at /Users/michael/.julia/dev/Plots/src/args.jl:1498
 [6] _subplot_setup(::Plots.Plot{Plots.GRBackend}, ::Dict{Symbol,Any}, ::Array{Dict{Symbol,Any},1}) at /Users/michael/.julia/dev/Plots/src/pipeline.jl:297
 [7] _plot!(::Plots.Plot{Plots.GRBackend}, ::Dict{Symbol,Any}, ::Tuple{UnitRange{Int64}}) at ./logging.jl:314
 [8] #plot#134(::Base.Iterators.Pairs{Symbol,Symbol,Tuple{Symbol},NamedTuple{(:seriestype,),Tuple{Symbol}}}, ::Function, ::UnitRange{Int64}) at /Users/michael/.julia/dev/Plots/src/plot.jl:57
 [9] #plot at ./none:0 [inlined]
 [10] #scatter#310 at /Users/michael/.julia/packages/RecipesBase/hOgg/src/RecipesBase.jl:384 [inlined]
 [11] scatter(::UnitRange{Int64}) at /Users/michael/.julia/packages/RecipesBase/hOgg/src/RecipesBase.jl:384
 [12] top-level scope at none:0
```

**Comment by schmrlng** [comment]
Thanks for fixing Plots up! Not sure if this is a known issue, but there's also the broken Requires.jl interaction below. It may be that deleting this [line](https://github.com/JuliaPlots/Plots.jl/blob/340cd0a1fe8bdddfb078e9fbd93d8cf4995cb134/src/backends/hdf5.jl#L132) is a sufficient workaround in the short term, but I don't know the original rationale for using `Nullable` in that dictionary/don't know the best way to fix it (a less hacky workaround would probably be to introduce the package dependency [Nullables.jl](https://github.com/JuliaArchive/Nullables.jl), but this is probably still sub-optimal with respect to some form of `Union{T, Nothing}`).
```julia
  | | |_| | | | (_| |  |  Version 0.7.0 (2018-08-08 06:46 UTC)
 _/ |\__'_|_|_|\__'_|  |
|__/                   |  x86_64-linux-gnu

julia> using Plots

julia> using HDF5
WARNING: importing deprecated binding Base.Nullable into Plots.
┌ Warning: Error requiring HDF5 from Plots:
│ LoadError: MethodError: Cannot `convert` an object of type typeof(Base.Nullable) to an object of type Type
│ Closest candidates are:
│   convert(::Type{Type}, !Matched::Type) at essentials.jl:155
│   convert(::Type{T}, !Matched::T) where T at essentials.jl:154
│ Stacktrace:
│  [1] setindex!(::Dict{String,Type}, ::Function, ::String) at ./dict.jl:381
│  [2] Dict{String,Type}(::Pair{String,DataType}, ::Vararg{Pair,N} where N) at ./dict.jl:113
│  [3] top-level scope at /home/schmrlng/.julia/packages/Plots/8ptoM/src/backends/hdf5.jl:109
│  [4] include at ./boot.jl:317 [inlined]
│  [5] include_relative(::Module, ::String) at ./loading.jl:1038
│  [6] include at ./sysimg.jl:29 [inlined]
│  [7] include(::String) at /home/schmrlng/.julia/packages/Plots/8ptoM/src/Plots.jl:1
│  [8] top-level scope at none:0
│  [9] eval at ./boot.jl:319 [inlined]
│  [10] eval at /home/schmrlng/.julia/packages/Plots/8ptoM/src/Plots.jl:1 [inlined]
│  [11] (::getfield(Plots, Symbol("##267#291")))() at /home/schmrlng/.julia/packages/Requires/9Jse8/src/require.jl:67
│  [12] err(::getfield(Plots, Symbol("##267#291")), ::Module, ::String) at /home/schmrlng/.julia/packages/Requires/9Jse8/src/require.jl:38
│  [13] #266 at /home/schmrlng/.julia/packages/Requires/9Jse8/src/require.jl:66 [inlined]
│  [14] withpath(::getfield(Plots, Symbol("##266#290")), ::String) at /home/schmrlng/.julia/packages/Requires/9Jse8/src/require.jl:28
│  [15] (::getfield(Plots, Symbol("##265#289")))() at /home/schmrlng/.julia/packages/Requires/9Jse8/src/require.jl:65
│  [16] #invokelatest#1 at ./essentials.jl:691 [inlined]
│  [17] invokelatest at ./essentials.jl:690 [inlined]
│  [18] #3 at /home/schmrlng/.julia/packages/Requires/9Jse8/src/require.jl:19 [inlined]
│  [19] iterate at ./generator.jl:47 [inlined]
│  [20] _collect(::Array{Function,1}, ::Base.Generator{Array{Function,1},getfield(Requires, Symbol("##3#4"))}, ::Base.EltypeUnknown, ::Base.HasShape{1}) at ./array.jl:632
│  [21] collect_similar at ./array.jl:561 [inlined]
│  [22] map at ./abstractarray.jl:1995 [inlined]
│  [23] loadpkg(::Base.PkgId) at /home/schmrlng/.julia/packages/Requires/9Jse8/src/require.jl:19
│  [24] #invokelatest#1 at ./essentials.jl:691 [inlined]
│  [25] invokelatest at ./essentials.jl:690 [inlined]
│  [26] require(::Base.PkgId) at ./loading.jl:855
│  [27] require(::Module, ::Symbol) at ./logging.jl:311
│  [28] eval(::Module, ::Any) at ./boot.jl:319
│  [29] eval_user_input(::Any, ::REPL.REPLBackend) at /home/schmrlng/code/oss/julia-0.7/usr/share/julia/stdlib/v0.7/REPL/src/REPL.jl:85
│  [30] macro expansion at /home/schmrlng/code/oss/julia-0.7/usr/share/julia/stdlib/v0.7/REPL/src/REPL.jl:117 [inlined]
│  [31] (::getfield(REPL, Symbol("##28#29")){REPL.REPLBackend})() at ./task.jl:262
│ in expression starting at /home/schmrlng/.julia/packages/Plots/8ptoM/src/backends/hdf5.jl:107
└ @ Requires ~/.julia/packages/Requires/9Jse8/src/require.jl:40

(v0.7) pkg> st
    Status `~/.julia/environments/v0.7/Project.toml`
...
  [f67ccb44] HDF5 v0.9.3
  [91a5bcdd] Plots v0.18.0+ #master (https://github.com/JuliaPlots/Plots.jl.git)
```

**Comment by melspectrum** [comment]
similar errors here

`MethodError: no method matching Array{Dict{Symbol,Any},1}(::Int64)
Closest candidates are:
  Array{Dict{Symbol,Any},1}() where T at boot.jl:413
  Array{Dict{Symbol,Any},1}(!Matched::UndefInitializer, !Matched::Int64) where T at boot.jl:394
  Array{Dict{Symbol,Any},1}(!Matched::UndefInitializer, !Matched::Int64...) where {T, N} at boot.jl:400
  ...

Stacktrace:
 [1] plotly_series_segments(::Plots.Series, ::Dict{Symbol,Any}, ::Array{Int64,1}, ::Array{Float64,1}, ::Nothing) at /home/redpanda/.julia/packages/Plots/U83Qe/src/backends/plotly.jl:710
 [2] plotly_series(::Plots.Plot{Plots.PlotlyBackend}, ::Plots.Series) at /home/redpanda/.julia/packages/Plots/U83Qe/src/backends/plotly.jl:574
 [3] plotly_series(::Plots.Plot{Plots.PlotlyBackend}) at /home/redpanda/.julia/packages/Plots/U83Qe/src/backends/plotly.jl:873
 [4] plotly_series_json at /home/redpanda/.julia/packages/Plots/U83Qe/src/backends/plotly.jl:879 [inlined]
 [5] html_body(::Plots.Plot{Plots.PlotlyBackend}, ::Nothing) at /home/redpanda/.julia/packages/Plots/U83Qe/src/backends/plotly.jl:897
 [6] html_body at /home/redpanda/.julia/packages/Plots/U83Qe/src/backends/plotly.jl:892 [inlined]
 [7] _show(::Base.GenericIOBuffer{Array{UInt8,1}}, ::MIME{Symbol("text/html")}, ::Plots.Plot{Plots.PlotlyBackend}) at /home/redpanda/.julia/packages/Plots/U83Qe/src/backends/plotly.jl:919
 [8] show(::Base.GenericIOBuffer{Array{UInt8,1}}, ::MIME{Symbol("text/html")}, ::Plots.Plot{Plots.PlotlyBackend}) at /home/redpanda/.julia/packages/Plots/U83Qe/src/output.jl:206
 [9] #sprint#325(::Nothing, ::Int64, ::Function, ::Function, ::MIME{Symbol("text/html")}, ::Vararg{Any,N} where N) at ./strings/io.jl:101
 [10] sprint(::Function, ::MIME{Symbol("text/html")}, ::Vararg{Any,N} where N) at ./strings/io.jl:97
 [11] display_dict(::Plots.Plot{Plots.PlotlyBackend}) at /home/redpanda/.julia/packages/Plots/U83Qe/src/init.jl:59
 [12] #invokelatest#1 at ./essentials.jl:686 [inlined]
 [13] invokelatest at ./essentials.jl:685 [inlined]
 [14] execute_request(::ZMQ.Socket, ::IJulia.Msg) at /home/redpanda/.julia/packages/IJulia/9RcVi/src/execute_request.jl:207
 [15] #invokelatest#1 at ./essentials.jl:686 [inlined]
 [16] invokelatest at ./essentials.jl:685 [inlined]
 [17] eventloop(::ZMQ.Socket) at /home/redpanda/.julia/packages/IJulia/9RcVi/src/eventloop.jl:8
 [18] (::getfield(IJulia, Symbol("##15#18")))() at ./task.jl:259`

**Comment by ChrisRackauckas** [comment]
The Plotly backend still seems to have a lot of issues on v1.0. I can't get it to work.

**Comment by mkborregaard** [comment]
could you be more specific?

**Comment by mkborregaard** [comment]
I mean it works for me when I try it.

**Comment by espintos** [comment]
Fresh Julia 1.0 installation here:
```
[ Info: Precompiling Plots [91a5bcdd-55d7-5caf-9e0b-520d859cae80]
ERROR: InitError: LoadError: MethodError: no method matching show(::Base.TTY, ::MIME{Symbol("text/html")}, ::String)
Closest candidates are:
  show(::IO, ::MIME{Symbol("text/plain")}, ::Any) at sysimg.jl:194
  show(::IO, ::MIME{Symbol("text/html")}, ::Method; kwtype) at methodshow.jl:241
  show(::IO, ::MIME{Symbol("text/html")}, ::Base.MethodList) at methodshow.jl:290
  ...
Stacktrace:
 [1] display(::TextDisplay, ::MIME{Symbol("text/html")}, ::String) at .\multimedia.jl:211
 [2] display(::MIME{Symbol("text/html")}, ::String) at .\multimedia.jl:301
 [3] display(::String, ::String) at .\multimedia.jl:179
 [4] top-level scope at C:\Users\epintos\.julia\packages\Plots\EJpx2\src\backends\plotly.jl:95
 [5] include at .\boot.jl:317 [inlined]
 [6] include_relative(::Module, ::String) at .\loading.jl:1038
 [7] include at .\sysimg.jl:29 [inlined]
 [8] include at C:\Users\epintos\.julia\packages\Plots\EJpx2\src\Plots.jl:1 [inlined]
 [9] __init__() at C:\Users\epintos\.julia\packages\Plots\EJpx2\src\init.jl:19
 [10] _include_from_serialized(::String, ::Array{Any,1}) at .\loading.jl:627
 [11] _require_from_serialized(::String) at .\loading.jl:678
 [12] macro expansion at .\logging.jl:317 [inlined]
 [13] _require(::Base.PkgId) at .\loading.jl:941
 [14] require(::Base.PkgId) at .\loading.jl:852
 [15] macro expansion at .\logging.jl:311 [inlined]
 [16] require(::Module, ::Symbol) at .\loading.jl:834
in expression starting at C:\Users\epintos\.julia\packages\Plots\EJpx2\src\backends\plotly.jl:94
during initialization of module Plots
```

**Comment by BeastyBlacksmith** [comment]
Is there anything left from the 1.0 transition?

**Comment by daschw** [comment]
I don't think so.

**Comment by BeastyBlacksmith** [comment]
I'll close this then. Please reopen, if appropriate.
