### ISSUE TITLE
PGFPlotsX meta-issue

### ISSUE THREAD

**Issue by BeastyBlacksmith** [JuliaPlots/Plots.jl#2290]
I start to collect what is missing:

- [ ] allow files as input data
- [ ] fix histogram2d
- [ ] implement fillranges with fillbetween
- [ ] interface for filling between functions
- [ ] interface for patch plots
- [ ] fix layouts
- [x] can't plot two series with fillrange (https://github.com/JuliaPlots/Plots.jl/issues/2290#issuecomment-560427043)
- [x] `heatmap(1:2,1:2,[1 2; 3 4])` only shows a black square

**Comment by daschw** [comment]
Can't plot two series with fillrange:
```julia
julia> plot(rand(10, 2), fillrange = 0)
! Illegal parameter number in definition of \pgfplots@curplotlist.
<to be read again>
1
l.118 \end{groupplot}

Error showing value of type Plots.Plot{Plots.PGFPlotsXBackend}:
ERROR: The latex command `lualatex jl_AE10.tmp.tex` failed
Stacktrace:
 [1] error(::String) at .\error.jl:33
 [2] #savepdf#71(::PGFPlotsX.LaTeXEngine, ::Array{String,1}, ::Int64, ::String, ::typeof(PGFPlotsX.savepdf), ::String, ::PGFPlotsX.TikzDocument) at C:\Users\Daniel\.julia\packages\PGFPlotsX\K4i95\src\tikzdocument.jl:196
 [3] #savepdf at .\none:0 [inlined]
 [4] #savepng#73(::PGFPlotsX.LaTeXEngine, ::Array{String,1}, ::Int64, ::typeof(PGFPlotsX.savepng), ::String, ::PGFPlotsX.TikzDocument) at C:\Users\Daniel\.julia\packages\PGFPlotsX\K4i95\src\tikzdocument.jl:322
 [5] #savepng at .\none:0 [inlined]
 [6] #save#65(::Bool, ::PGFPlotsX.LaTeXEngine, ::Array{String,1}, ::Int64, ::Bool, ::typeof(PGFPlotsX.save), ::String, ::PGFPlotsX.TikzDocument) at C:\Users\Daniel\.julia\packages\PGFPlotsX\K4i95\src\tikzdocument.jl:87
 [7] (::PGFPlotsX.var"#kw##save")(::NamedTuple{(:showing_ide,),Tuple{Bool}}, ::typeof(PGFPlotsX.save), ::String, ::PGFPlotsX.TikzDocument) at .\none:0
 [8] show(::IOContext{Base64.Base64EncodePipe}, ::MIME{Symbol("image/png")}, ::PGFPlotsX.TikzDocument) at C:\Users\Daniel\.julia\packages\PGFPlotsX\K4i95\src\tikzdocument.jl:333
 [9] _show(::IOContext{Base64.Base64EncodePipe}, ::MIME{Symbol("image/png")}, ::Plots.Plot{Plots.PGFPlotsXBackend}) at C:\Users\Daniel\.julia\dev\Plots\src\backends\pgfplotsx.jl:835
 [10] _showjuno at C:\Users\Daniel\.julia\dev\Plots\src\output.jl:267 [inlined]
 [11] showjuno(::IOContext{Base64.Base64EncodePipe}, ::MIME{Symbol("image/png")}, ::Plots.Plot{Plots.PGFPlotsXBackend}) at C:\Users\Daniel\.julia\dev\Plots\src\output.jl:249
 [12] show(::IOContext{Base64.Base64EncodePipe}, ::MIME{Symbol("image/png")}, ::Plots.Plot{Plots.PGFPlotsXBackend}) at C:\Users\Daniel\.julia\dev\Plots\src\output.jl:196
 [13] #base64encode#3(::IOContext{Base.GenericIOBuffer{Array{UInt8,1}}}, ::typeof(Base64.base64encode), ::Function, ::MIME{Symbol("image/png")}, ::Vararg{Any,N} where N) at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\Base64\src\encode.jl:208
 [14] #base64encode at .\none:0 [inlined]
 [15] _binstringmime at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\Base64\src\Base64.jl:46 [inlined]
 [16] #stringmime#6(::IOContext{Base.GenericIOBuffer{Array{UInt8,1}}}, ::typeof(Base64.stringmime), ::MIME{Symbol("image/png")}, ::Plots.Plot{Plots.PGFPlotsXBackend}) at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\Base64\src\Base64.jl:43
 [17] (::Base64.var"#kw##stringmime")(::NamedTuple{(:context,),Tuple{IOContext{Base.GenericIOBuffer{Array{UInt8,1}}}}}, ::typeof(Base64.stringmime), ::MIME{Symbol("image/png")}, ::Plots.Plot{Plots.PGFPlotsXBackend}) at .\none:0
 [18] #stringmime#7(::IOContext{Base.GenericIOBuffer{Array{UInt8,1}}}, ::typeof(Base64.stringmime), ::String, ::Plots.Plot{Plots.PGFPlotsXBackend}) at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\Base64\src\Base64.jl:44
 [19] #stringmime at .\none:0 [inlined]
 [20] displayinplotpane(::Plots.Plot{Plots.PGFPlotsXBackend}) at C:\Users\Daniel\.julia\packages\Atom\lBERI\src\display\showdisplay.jl:78
 [21] display(::Atom.JunoDisplay, ::Plots.Plot{Plots.PGFPlotsXBackend}) at C:\Users\Daniel\.julia\packages\Atom\lBERI\src\display\showdisplay.jl:112
 [22] display(::Any) at .\multimedia.jl:323
 [23] #invokelatest#1 at .\essentials.jl:709 [inlined]
 [24] invokelatest at .\essentials.jl:708 [inlined]
 [25] print_response(::IO, ::Any, ::Bool, ::Bool, ::Any) at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\REPL\src\REPL.jl:156
 [26] print_response(::REPL.AbstractREPL, ::Any, ::Bool, ::Bool) at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\REPL\src\REPL.jl:141
 [27] (::REPL.var"#do_respond#38"{Bool,Atom.var"#176#177",REPL.LineEditREPL,REPL.LineEdit.Prompt})(::Any, ::Any, ::Any) at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\REPL\src\REPL.jl:719
 [28] #invokelatest#1 at .\essentials.jl:709 [inlined]
 [29] invokelatest at .\essentials.jl:708 [inlined]
 [30] run_interface(::REPL.Terminals.TextTerminal, ::REPL.LineEdit.ModalInterface, ::REPL.LineEdit.MIState) at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\REPL\src\LineEdit.jl:2306
 [31] run_frontend(::REPL.LineEditREPL, ::REPL.REPLBackendRef) at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\REPL\src\REPL.jl:1045
 [32] run_repl(::REPL.AbstractREPL, ::Any) at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\REPL\src\REPL.jl:201
 [33] (::Base.var"#770#772"{Bool,Bool,Bool,Bool})(::Module) at .\client.jl:382
 [34] #invokelatest#1 at .\essentials.jl:709 [inlined]
 [35] invokelatest at .\essentials.jl:708 [inlined]
 [36] run_main_repl(::Bool, ::Bool, ::Bool, ::Bool, ::Bool) at .\client.jl:366
 [37] exec_options(::Base.JLOptions) at .\client.jl:304
 [38] _start() at .\client.jl:460
```

**Comment by BeastyBlacksmith** [comment]
did it auto close, because I referenced it?

**Comment by daschw** [comment]
Probably 😄
