### ISSUE TITLE
Aspect ratio meta-issue

### ISSUE THREAD

**Issue by mkborregaard** [JuliaPlots/Plots.jl#2424]
Would be nice to work over and consider how aspect ratio works in Plots.
The main issue being the relationship between plot aspect ratio and data aspect, and how they behave in layouts. 
Relevant issues:
- [] Keep colorbar next to contour plot when aspect ratio is changed in PyPlot #484
- [] Match plot and image aspect ratios #1238
- [] `aspect_ratio = :equal` with `legend = false` not correct for `plotlyjs()` #1603
- [] use equal aspect ratio by default for images? #1898
- [] aspect_ratio=:equal in 3d plots doesn't always work? #1949
- [] `aspect_ratio` breaks `link` #1990
- [] `aspect_ratio` does not fully work with pgfplots() #2037

**Comment by rjpower4** [comment]
Does [this](https://github.com/matplotlib/matplotlib/pull/17515) merge assist in any way?

**Comment by FelixBenning** [comment]
It seems like `aspect_ratio=1` breaks layouts:

![visualize_gd](https://user-images.githubusercontent.com/29106652/125137893-e489e980-e10d-11eb-8346-dc68257f7392.png)

```julia
losssurface = plot(-5:0.1:5, -5:0.1:5, f, st=:contour, title="Losssurface")
plot!(
	losssurface,
	decent_steps[1,:], 
	decent_steps[2,:],
	markershape=:circle,
	arrow=:arrow,
	label="Path of Gradient Decent",
	aspect_ratio=1
)
loss = plot(
	mapslices(f, decent_steps;dims=(1))', 
	st=:scatter, 
	label=missing, 
	title="Loss", 
	xlabel="Iteration",
)
plot(losssurface, loss, layout=grid(1,2, widths=[0.7,0.3]))
```

Without the `aspect_ratio=1` the plots are well aligned

![visualize_gd](https://user-images.githubusercontent.com/29106652/125138071-43e7f980-e10e-11eb-8c81-102c9b5a4bca.png)

using the keyword `heights` did not seem to have an effect, but I still might be missing some options

**Comment by toma-vlad** [comment]
> 
> 
> It seems like `aspect_ratio=1` breaks layouts:
> 
> ![visualize_gd](https://user-images.githubusercontent.com/29106652/125137893-e489e980-e10d-11eb-8346-dc68257f7392.png)
> 
> ```julia
> losssurface = plot(-5:0.1:5, -5:0.1:5, f, st=:contour, title="Losssurface")
> plot!(
> 	losssurface,
> 	decent_steps[1,:], 
> 	decent_steps[2,:],
> 	markershape=:circle,
> 	arrow=:arrow,
> 	label="Path of Gradient Decent",
> 	aspect_ratio=1
> )
> loss = plot(
> 	mapslices(f, decent_steps;dims=(1))', 
> 	st=:scatter, 
> 	label=missing, 
> 	title="Loss", 
> 	xlabel="Iteration",
> )
> plot(losssurface, loss, layout=grid(1,2, widths=[0.7,0.3]))
> ```
> 
> Without the `aspect_ratio=1` the plots are well aligned
> 
> ![visualize_gd](https://user-images.githubusercontent.com/29106652/125138071-43e7f980-e10e-11eb-8c81-102c9b5a4bca.png)
> 
> using the keyword `heights` did not seem to have an effect, but I still might be missing some options

I have had a similar issues, mine manifested whenever i was trying to look at the axes limits. 

See https://github.com/JuliaPlots/Plots.jl/issues/3479#issue-880595265
