### ISSUE TITLE
PGFPlots meta-issue

### ISSUE THREAD

**Issue by tbreloff** [JuliaPlots/Plots.jl#318]
- [ ] clims (#293)
- [ ] pgfplots setup/install automation? (#134)
- [ ] line segments, `line_z` (#218)
- [ ] handle discrete axes
- [ ] dpi (#173)
- [ ] ticks (#434)
- [ ] fillrange: `plot(randn(10), fillrange=randn(10)+2)`
- [ ] ribbon: `plot(randn(10), ribbon = (2,1))`

**Comment by codles** [comment]
Specifying `xticks` has no effect on output figure with PGFPlots.

**Comment by tbreloff** [comment]
You're right... I added it to the list.  Thanks.

**Comment by baggepinnen** [comment]
Attributes `fillrange` and `ribbon` does not work as intended with backend `pgfplots`
```julia
pgfplots()
plot(randn(10), fillrange=randn(10)+2)
plot(randn(10), ribbon = [2,1])
plot(randn(10), ribbon = (ones(10),2ones(10)))
```

**Comment by pkofod** [comment]
Can I ask what "handle discrete axis" means here?

**Comment by tbreloff** [comment]
when the axes values are discrete (symbols, strings,, or something else).  I'll probably need to help with that one.

**Comment by pkofod** [comment]
ah, so we want to place something at 1, 2, 3, 4 with custom tick labels ?

**Comment by mkborregaard** [comment]
I have this backend not working at all on Mac.
```julia
using Plots
pgfplots()
plot(1:10,1:10)
Error saving as SVG
Error showing value of type Plots.Plot{Plots.PGFPlotsBackend}:
ERROR: could not spawn `pdf2svg /var/folders/b8/rvm2dk495f74088ssh9v2l8r0000gn/T/juliaGKHu1L.pdf /var/folders/b8/rvm2dk495f74088ssh9v2l8r0000gn/T/juliaGKHu1L.svg`: no such file or directory (ENOENT)
Stacktrace:
 [1] _jl_spawn(::String, ::Array{String,1}, ::Ptr{Void}, ::Base.Process, ::Base.DevNullStream, ::Base.DevNullStream, ::Base.DevNullStream) at ./process.jl:360
 [2] #373 at ./process.jl:512 [inlined]
 [3] setup_stdio(::Base.##373#374{Cmd}, ::Tuple{Base.DevNullStream,Base.DevNullStream,Base.DevNullStream}) at ./process.jl:499
 [4] #spawn#372(::Nullable{Base.ProcessChain}, ::Function, ::Cmd, ::Tuple{Base.DevNullStream,Base.DevNullStream,Base.DevNullStream}) at ./process.jl:511
 [5] (::Base.#kw##spawn)(::Array{Any,1}, ::Base.#spawn, ::Cmd, ::Tuple{Base.DevNullStream,Base.DevNullStream,Base.DevNullStream}) at ./<missing>:0
 [6] save(::TikzPictures.SVG, ::TikzPictures.TikzPicture) at /Users/michael/.julia/v0.6/TikzPictures/src/TikzPictures.jl:264
 [7] _display(::Plots.Plot{Plots.PGFPlotsBackend}) at /Users/michael/.julia/v0.6/Plots/src/backends/pgfplots.jl:424
 [8] display(::Base.REPL.REPLDisplay{Base.REPL.LineEditREPL}, ::MIME{Symbol("text/plain")}, ::Plots.Plot{Plots.PGFPlotsBackend}) at /Users/michael/.julia/v0.6/Plots/src/output.jl:138
 [9] display(::Base.REPL.REPLDisplay{Base.REPL.LineEditREPL}, ::Plots.Plot{Plots.PGFPlotsBackend}) at ./REPL.jl:125
 [10] display(::Plots.Plot{Plots.PGFPlotsBackend}) at ./multimedia.jl:194
 [11] eval(::Module, ::Any) at ./boot.jl:235
 [12] print_response(::Base.Terminals.TTYTerminal, ::Any, ::Void, ::Bool, ::Bool, ::Void) at ./REPL.jl:144
 [13] print_response(::Base.REPL.LineEditREPL, ::Any, ::Void, ::Bool, ::Bool) at ./REPL.jl:129
 [14] (::Base.REPL.#do_respond#16{Bool,Base.REPL.##26#36{Base.REPL.LineEditREPL,Base.REPL.REPLHistoryProvider},Base.REPL.LineEditREPL,Base.LineEdit.Prompt})(::Base.LineEdit.MIState, ::Base.AbstractIOBuffer{Array{UInt8,1}}, ::Bool) at ./REPL.jl:646
```
I saw that on Ubuntu the pdf2svg needs to be installed manually. I don't think that tool works on a Mac. Is it simply meant to be linux/windows only, or have I flipped some setting wrong?

**Comment by bobbielf2** [comment]
@mkborregaard I am using Mac too and it works on my computer. You need both PGFPlots (the latex package, not the Julia package) and pdf2svg. I installed TeXShop on my Mac so pdf2svg is already included, so I only needed to install [PGFPlots](http://pgfplots.sourceforge.net/).

**Comment by mkborregaard** [comment]
You're right, I felt to update here that I have it working great now.

**Comment by otobrzo** [comment]
Is there possibility to change the font family?
I would like to save figure directly to pdf or svg format (otherwise I would edit tex source)

I have found this: 
[font family](https://tex.stackexchange.com/questions/118678/change-font-family-in-pgfplots-followup)

you need to pass `font=\sffamily\sansmath` to

`\begin{tikzpicture}[font=\sffamily\sansmath]`

**Comment by BeastyBlacksmith** [comment]
closing in favor of https://github.com/JuliaPlots/Plots.jl/issues/2290
