### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by JackDevine** [JuliaPlots/Plots.jl#5339]
A lot has happened on master since v0.4.0 and some of it is slightly breaking, so we should definitely make a new release.

Summary of changes made:
* Each edge has its own series: JuliaPlots/GraphRecipes.jl#57 
* Edge labels can be specified through the `edgelabel` kwarg JuliaPlots/GraphRecipes.jl#65 
* Directed graphs can now be handled and have arrows JuliaPlots/GraphRecipes.jl#67 
* Nodes are no longer Plots.jl markers. Meaning that `markershape` and `markersize` are now replaced with `nodeshape` and `nodesize` JuliaPlots/GraphRecipes.jl#67 
* Graphs with self edges can be visualized JuliaPlots/GraphRecipes.jl#68 
* Mulitgraphs can be visualized and `edgelabels` accepts triples to specify the labels  JuliaPlots/GraphRecipes.jl#71
* Many of the keyword arguments to `grahplot` have aliases JuliaPlots/GraphRecipes.jl#88

Issues to be fixed before new release:

- [x] JuliaPlots/Plots.jl#5342 
- [x] JuliaPlots/Plots.jl#5349 
- [x] JuliaPlots/Plots.jl#5344 
- [x] JuliaPlots/Plots.jl#5345

I may add to the list and I am open for suggestions to add to the list. I believe that the fact that we have moved away from Plots.jl markers warrants a major release (upgrade to v0.5.0). Fixing JuliaPlots/Plots.jl#5344 will slightly improve things, however, ultimately, we have made a break from the old GraphRecipes in JuliaPlots/GraphRecipes.jl#67.

~~In the meantime, the README gives incorrect results for people who are not on master (see JuliaPlots/Plots.jl#5341). I guess that nobody expected the new release to take this long. Perhaps we should put a warning on the readme? Not sure.~~ EDIT: Fixed in JuliaPlots/GraphRecipes.jl#88
