### ISSUE TITLE
GLVisualize backend state tracker

### ISSUE THREAD

**Issue by SimonDanisch** [JuliaPlots/Plots.jl#577]
- [ ] cache RenderObjects for way better animation performance
- [ ] implement pie charts
- [ ] draw arrow heads as rotated particles
- [ ] legend for colormap
- [ ] better 3D axis
- [ ] better interaction of camera with axis and labels

**Comment by mkborregaard** [comment]
On my computer this backend throws an error on the `post_empty` call, because Plots does not import Reactive. This means that the backend doesn't work at all in Atom; it works but errors in the REPL. Is this something that will just be fixed by a reorganization where the backend will live in Plots_GLVisualize, that then is free to import Reactive?`

**Comment by SimonDanisch** [comment]
No ;) But this is already fixed on my branch ... Try checking out `sd/dev`!

**Comment by mkborregaard** [comment]
Nice, when do you plan to merge? Is the glvisualize backend otherwise ready for everyday use?

**Comment by daschw** [comment]
Closing as GLVisualize is no longer supported.
